const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "7061124469";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_09_29_10_17_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAwLFxuICAgICAgICAxNjcsXG4gICAgICAgIDU1LFxuICAgICAgICA5OCxcbiAgICAgICAgNDAsXG4gICAgICAgIDE4NyxcbiAgICAgICAgNjAsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTY3LFxuICAgICAgICAyMTMsXG4gICAgICAgIDc5LFxuICAgICAgICA1MixcbiAgICAgICAgNzAsXG4gICAgICAgIDc4LFxuICAgICAgICAxOCxcbiAgICAgICAgMTA0LFxuICAgICAgICAxMSxcbiAgICAgICAgMjM3LFxuICAgICAgICAyMTAsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTUzLFxuICAgICAgICAyMDIsXG4gICAgICAgIDEzLFxuICAgICAgICAxNzgsXG4gICAgICAgIDY5LFxuICAgICAgICAyMTksXG4gICAgICAgIDcwLFxuICAgICAgICAxOTIsXG4gICAgICAgIDIxLFxuICAgICAgICAzMCxcbiAgICAgICAgMjE1LFxuICAgICAgICA5NVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2MSxcbiAgICAgICAgMTcsXG4gICAgICAgIDIxLFxuICAgICAgICAxOTcsXG4gICAgICAgIDEwMixcbiAgICAgICAgNzQsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTI0LFxuICAgICAgICA0MyxcbiAgICAgICAgMjQ2LFxuICAgICAgICAxNCxcbiAgICAgICAgMTc5LFxuICAgICAgICA1NixcbiAgICAgICAgMjA1LFxuICAgICAgICAzNixcbiAgICAgICAgMTU5LFxuICAgICAgICA2OCxcbiAgICAgICAgMTksXG4gICAgICAgIDUxLFxuICAgICAgICAxMzEsXG4gICAgICAgIDM2LFxuICAgICAgICA0MixcbiAgICAgICAgMjYsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTEyLFxuICAgICAgICAyMyxcbiAgICAgICAgMSxcbiAgICAgICAgMjM2LFxuICAgICAgICAxNjMsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjM2LFxuICAgICAgICA5NlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODgsXG4gICAgICAgIDQ4LFxuICAgICAgICAxNTUsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMzQsXG4gICAgICAgIDE3OSxcbiAgICAgICAgODksXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjYsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMzMsXG4gICAgICAgIDU3LFxuICAgICAgICAxMDgsXG4gICAgICAgIDE0LFxuICAgICAgICAxNzYsXG4gICAgICAgIDU1LFxuICAgICAgICA0NyxcbiAgICAgICAgMTEsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjgsXG4gICAgICAgIDU1LFxuICAgICAgICA5MCxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxNzUsXG4gICAgICAgIDc1LFxuICAgICAgICAyMSxcbiAgICAgICAgOTAsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTIsXG4gICAgICAgIDc2LFxuICAgICAgICAxMzIsXG4gICAgICAgIDEyMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0LFxuICAgICAgICAxNzQsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTQyLFxuICAgICAgICA3NCxcbiAgICAgICAgMTQxLFxuICAgICAgICAyMjMsXG4gICAgICAgIDEzMCxcbiAgICAgICAgNzAsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTg5LFxuICAgICAgICA3LFxuICAgICAgICAxODEsXG4gICAgICAgIDk1LFxuICAgICAgICAxODUsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMjIwLFxuICAgICAgICAyMTcsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjEsXG4gICAgICAgIDIxMSxcbiAgICAgICAgNTgsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMjMwLFxuICAgICAgICAxNTQsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTA0LFxuICAgICAgICAxNTEsXG4gICAgICAgIDI4LFxuICAgICAgICAxMjEsXG4gICAgICAgIDMxLFxuICAgICAgICAxMDJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0OCxcbiAgICAgICAgNDksXG4gICAgICAgIDIyNyxcbiAgICAgICAgNCxcbiAgICAgICAgNTksXG4gICAgICAgIDE0MyxcbiAgICAgICAgNzAsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTEzLFxuICAgICAgICA3NixcbiAgICAgICAgMTcxLFxuICAgICAgICAyMDYsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMjEzLFxuICAgICAgICAxMTAsXG4gICAgICAgIDc2LFxuICAgICAgICAxMDQsXG4gICAgICAgIDYxLFxuICAgICAgICAxMjIsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTYyLFxuICAgICAgICAxNTMsXG4gICAgICAgIDcyLFxuICAgICAgICAxMTEsXG4gICAgICAgIDgsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyNDIsXG4gICAgICAgIDk1LFxuICAgICAgICAxODUsXG4gICAgICAgIDE0OCxcbiAgICAgICAgOTVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTM0LFxuICAgICAgICAyMTUsXG4gICAgICAgIDE0LFxuICAgICAgICAyMDgsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjM2LFxuICAgICAgICAyMjAsXG4gICAgICAgIDEzLFxuICAgICAgICAxODYsXG4gICAgICAgIDE5MSxcbiAgICAgICAgNzIsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjQ4LFxuICAgICAgICAyMjIsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTU3LFxuICAgICAgICA3NCxcbiAgICAgICAgOTEsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTg3LFxuICAgICAgICAyMSxcbiAgICAgICAgMTM4LFxuICAgICAgICAxNDAsXG4gICAgICAgIDE5MCxcbiAgICAgICAgODIsXG4gICAgICAgIDIyLFxuICAgICAgICA0OCxcbiAgICAgICAgMTYwLFxuICAgICAgICAyMyxcbiAgICAgICAgMTEzLFxuICAgICAgICA2LFxuICAgICAgICAxMjZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDE4NSxcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMjUyLFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAxMjMsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAxMzMsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMTMxLFxuICAgICAgICAgIDEwNFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDE5OCxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICA4MCxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDk5XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTM2LFxuICAgICAgICAyMzYsXG4gICAgICAgIDUxLFxuICAgICAgICAxMzEsXG4gICAgICAgIDE5NyxcbiAgICAgICAgNyxcbiAgICAgICAgNjMsXG4gICAgICAgIDEzLFxuICAgICAgICAxMyxcbiAgICAgICAgMTI4LFxuICAgICAgICAyMTgsXG4gICAgICAgIDEwLFxuICAgICAgICAyMzgsXG4gICAgICAgIDEzNCxcbiAgICAgICAgNzksXG4gICAgICAgIDE2MixcbiAgICAgICAgOTMsXG4gICAgICAgIDQzLFxuICAgICAgICAxNjcsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMzksXG4gICAgICAgIDQ3LFxuICAgICAgICAxNDgsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTAwLFxuICAgICAgICA0NyxcbiAgICAgICAgMjcsXG4gICAgICAgIDE3OSxcbiAgICAgICAgNzksXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjQzLFxuICAgICAgICAxNTcsXG4gICAgICAgIDE5OCxcbiAgICAgICAgODgsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjAsXG4gICAgICAgIDQ1LFxuICAgICAgICA4MCxcbiAgICAgICAgODYsXG4gICAgICAgIDE1LFxuICAgICAgICAxMixcbiAgICAgICAgMTU4LFxuICAgICAgICAxODcsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTcwLFxuICAgICAgICA5MyxcbiAgICAgICAgMTAyLFxuICAgICAgICA0NyxcbiAgICAgICAgMjMxLFxuICAgICAgICAxMDUsXG4gICAgICAgIDEzMixcbiAgICAgICAgMjAwLFxuICAgICAgICAyNixcbiAgICAgICAgMTUxLFxuICAgICAgICA5MCxcbiAgICAgICAgMjA3LFxuICAgICAgICA2NCxcbiAgICAgICAgMTQ4LFxuICAgICAgICA0NixcbiAgICAgICAgMjM2LFxuICAgICAgICAxMjcsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMjYsXG4gICAgICAgIDhcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDksXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiWitXUjNFeW84djZ3Ynd6M2Njck1nQWpOVEhaYTVFZWROK3BSSnJtYXVVWT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwibzlwSlFFSGlUZVN5TkN6MEI5TGk2Z1wiLFxuICBcInBob25lSWRcIjogXCI3MjMzN2FlNS02YTg3LTQyNDItODVlMC1jYWQ2MGM2OWIwN2FcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTE3LFxuICAgICAgNzgsXG4gICAgICA0NyxcbiAgICAgIDE0NSxcbiAgICAgIDEwLFxuICAgICAgMTM3LFxuICAgICAgNDIsXG4gICAgICA0OCxcbiAgICAgIDEwNyxcbiAgICAgIDI0NSxcbiAgICAgIDQ4LFxuICAgICAgMjEwLFxuICAgICAgMTA5LFxuICAgICAgMTM4LFxuICAgICAgMTgsXG4gICAgICA1MSxcbiAgICAgIDIwNyxcbiAgICAgIDI5LFxuICAgICAgMTM4LFxuICAgICAgMTlcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNjMsXG4gICAgICAzMSxcbiAgICAgIDEzNSxcbiAgICAgIDIwNyxcbiAgICAgIDExOCxcbiAgICAgIDI0LFxuICAgICAgMTMzLFxuICAgICAgMjIwLFxuICAgICAgMjUxLFxuICAgICAgMTQ4LFxuICAgICAgMjIwLFxuICAgICAgMjEwLFxuICAgICAgMTY3LFxuICAgICAgMjE5LFxuICAgICAgMzIsXG4gICAgICA2NSxcbiAgICAgIDEwNSxcbiAgICAgIDE1NixcbiAgICAgIDQ2LFxuICAgICAgMTUwXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIjkzRldQUVFDXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ3MDYxMTI0NDY5OjEzQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCI0MDkzMTMwNjc3MDUzMjoxM0BsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNOZTAxUFlGRU51eHc3Z0dHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIlBUUUxzQWFQWEhjcWtWY1YxYmZZVXNKOFBBTWVrYXkvejRJWDhBMDdDMkE9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiTk5VOUp3cnpENjdDN3Nhbm1FU0U0V1gwd24yWmx0MnpIU0pTdTdPVHllNnRoWmJ1MWNWOC80Z0FwYjEzVEpySHVtOWp6bzZsUmxsakxxQklrMUNlRGc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiYTdtdWEwUHdoV0h0Uk5KMVJ5QUl0VHNBVVh1b29SaDdCdlB0QVRuOTRHNWlSaXZRY0xlcEd1Y3U1V2RSOE90TXBEK1dmaUFJeHpoVlhpTFZybmx1QXc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0NzA2MTEyNDQ2OToxM0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICA2LFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICA5MixcbiAgICAgICAgICAxMTksXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAxODMsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgMyxcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICA1OSxcbiAgICAgICAgICAxMSxcbiAgICAgICAgICA5NlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI5MTU3MzQyLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBQmgwXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFCaDAuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJSNlMyNlRmOWIvWWUwUnVJQitYMTJXazJIZ2NnL0R3VVlWYWNEZGR4SGFrPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE1OTEwMjQyMTAsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMl19LFwidGltZXN0YW1wXCI6XCIwXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
